// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worldcomm.proto

package worldcomm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WorldCommMessageType int32

const (
	WorldCommMessageType_UNKNOWN_MESSAGE_TYPE WorldCommMessageType = 0
	WorldCommMessageType_PING                 WorldCommMessageType = 1
	WorldCommMessageType_ADD_TOPIC            WorldCommMessageType = 2
	WorldCommMessageType_REMOVE_TOPIC         WorldCommMessageType = 3
	WorldCommMessageType_TOPIC                WorldCommMessageType = 4
)

var WorldCommMessageType_name = map[int32]string{
	0: "UNKNOWN_MESSAGE_TYPE",
	1: "PING",
	2: "ADD_TOPIC",
	3: "REMOVE_TOPIC",
	4: "TOPIC",
}

var WorldCommMessageType_value = map[string]int32{
	"UNKNOWN_MESSAGE_TYPE": 0,
	"PING":                 1,
	"ADD_TOPIC":            2,
	"REMOVE_TOPIC":         3,
	"TOPIC":                4,
}

func (x WorldCommMessageType) String() string {
	return proto.EnumName(WorldCommMessageType_name, int32(x))
}

func (WorldCommMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{0}
}

type WorldCommMessage struct {
	Type                 WorldCommMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=WorldCommMessageType" json:"type,omitempty"`
	Time                 float64              `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WorldCommMessage) Reset()         { *m = WorldCommMessage{} }
func (m *WorldCommMessage) String() string { return proto.CompactTextString(m) }
func (*WorldCommMessage) ProtoMessage()    {}
func (*WorldCommMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{0}
}

func (m *WorldCommMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldCommMessage.Unmarshal(m, b)
}
func (m *WorldCommMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldCommMessage.Marshal(b, m, deterministic)
}
func (m *WorldCommMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldCommMessage.Merge(m, src)
}
func (m *WorldCommMessage) XXX_Size() int {
	return xxx_messageInfo_WorldCommMessage.Size(m)
}
func (m *WorldCommMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldCommMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WorldCommMessage proto.InternalMessageInfo

func (m *WorldCommMessage) GetType() WorldCommMessageType {
	if m != nil {
		return m.Type
	}
	return WorldCommMessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *WorldCommMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type PingMessage struct {
	Type                 WorldCommMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=WorldCommMessageType" json:"type,omitempty"`
	Time                 float64              `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{1}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetType() WorldCommMessageType {
	if m != nil {
		return m.Type
	}
	return WorldCommMessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *PingMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type AddTopicMessage struct {
	Type                 WorldCommMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=WorldCommMessageType" json:"type,omitempty"`
	Time                 float64              `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	Topic                string               `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddTopicMessage) Reset()         { *m = AddTopicMessage{} }
func (m *AddTopicMessage) String() string { return proto.CompactTextString(m) }
func (*AddTopicMessage) ProtoMessage()    {}
func (*AddTopicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{2}
}

func (m *AddTopicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTopicMessage.Unmarshal(m, b)
}
func (m *AddTopicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTopicMessage.Marshal(b, m, deterministic)
}
func (m *AddTopicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTopicMessage.Merge(m, src)
}
func (m *AddTopicMessage) XXX_Size() int {
	return xxx_messageInfo_AddTopicMessage.Size(m)
}
func (m *AddTopicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTopicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AddTopicMessage proto.InternalMessageInfo

func (m *AddTopicMessage) GetType() WorldCommMessageType {
	if m != nil {
		return m.Type
	}
	return WorldCommMessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *AddTopicMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AddTopicMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type RemoveTopicMessage struct {
	Type                 WorldCommMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=WorldCommMessageType" json:"type,omitempty"`
	Time                 float64              `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	Topic                string               `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RemoveTopicMessage) Reset()         { *m = RemoveTopicMessage{} }
func (m *RemoveTopicMessage) String() string { return proto.CompactTextString(m) }
func (*RemoveTopicMessage) ProtoMessage()    {}
func (*RemoveTopicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{3}
}

func (m *RemoveTopicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTopicMessage.Unmarshal(m, b)
}
func (m *RemoveTopicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTopicMessage.Marshal(b, m, deterministic)
}
func (m *RemoveTopicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTopicMessage.Merge(m, src)
}
func (m *RemoveTopicMessage) XXX_Size() int {
	return xxx_messageInfo_RemoveTopicMessage.Size(m)
}
func (m *RemoveTopicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTopicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTopicMessage proto.InternalMessageInfo

func (m *RemoveTopicMessage) GetType() WorldCommMessageType {
	if m != nil {
		return m.Type
	}
	return WorldCommMessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *RemoveTopicMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *RemoveTopicMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type TopicMessage struct {
	Type                 WorldCommMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=WorldCommMessageType" json:"type,omitempty"`
	Time                 float64              `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	Topic                string               `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Alias                string               `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	Body                 []byte               `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TopicMessage) Reset()         { *m = TopicMessage{} }
func (m *TopicMessage) String() string { return proto.CompactTextString(m) }
func (*TopicMessage) ProtoMessage()    {}
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{4}
}

func (m *TopicMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMessage.Unmarshal(m, b)
}
func (m *TopicMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMessage.Marshal(b, m, deterministic)
}
func (m *TopicMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMessage.Merge(m, src)
}
func (m *TopicMessage) XXX_Size() int {
	return xxx_messageInfo_TopicMessage.Size(m)
}
func (m *TopicMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMessage proto.InternalMessageInfo

func (m *TopicMessage) GetType() WorldCommMessageType {
	if m != nil {
		return m.Type
	}
	return WorldCommMessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *TopicMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TopicMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *TopicMessage) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *TopicMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type PositionData struct {
	PositionX            float32  `protobuf:"fixed32,1,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY            float32  `protobuf:"fixed32,2,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	PositionZ            float32  `protobuf:"fixed32,3,opt,name=position_z,json=positionZ,proto3" json:"position_z,omitempty"`
	RotationX            float32  `protobuf:"fixed32,4,opt,name=rotation_x,json=rotationX,proto3" json:"rotation_x,omitempty"`
	RotationY            float32  `protobuf:"fixed32,5,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
	RotationZ            float32  `protobuf:"fixed32,6,opt,name=rotation_z,json=rotationZ,proto3" json:"rotation_z,omitempty"`
	RotationW            float32  `protobuf:"fixed32,7,opt,name=rotation_w,json=rotationW,proto3" json:"rotation_w,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionData) Reset()         { *m = PositionData{} }
func (m *PositionData) String() string { return proto.CompactTextString(m) }
func (*PositionData) ProtoMessage()    {}
func (*PositionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{5}
}

func (m *PositionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionData.Unmarshal(m, b)
}
func (m *PositionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionData.Marshal(b, m, deterministic)
}
func (m *PositionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionData.Merge(m, src)
}
func (m *PositionData) XXX_Size() int {
	return xxx_messageInfo_PositionData.Size(m)
}
func (m *PositionData) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionData.DiscardUnknown(m)
}

var xxx_messageInfo_PositionData proto.InternalMessageInfo

func (m *PositionData) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *PositionData) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

func (m *PositionData) GetPositionZ() float32 {
	if m != nil {
		return m.PositionZ
	}
	return 0
}

func (m *PositionData) GetRotationX() float32 {
	if m != nil {
		return m.RotationX
	}
	return 0
}

func (m *PositionData) GetRotationY() float32 {
	if m != nil {
		return m.RotationY
	}
	return 0
}

func (m *PositionData) GetRotationZ() float32 {
	if m != nil {
		return m.RotationZ
	}
	return 0
}

func (m *PositionData) GetRotationW() float32 {
	if m != nil {
		return m.RotationW
	}
	return 0
}

type ProfileData struct {
	AvatarType           string   `protobuf:"bytes,1,opt,name=avatar_type,json=avatarType,proto3" json:"avatar_type,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PublicKey            string   `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileData) Reset()         { *m = ProfileData{} }
func (m *ProfileData) String() string { return proto.CompactTextString(m) }
func (*ProfileData) ProtoMessage()    {}
func (*ProfileData) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{6}
}

func (m *ProfileData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileData.Unmarshal(m, b)
}
func (m *ProfileData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileData.Marshal(b, m, deterministic)
}
func (m *ProfileData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileData.Merge(m, src)
}
func (m *ProfileData) XXX_Size() int {
	return xxx_messageInfo_ProfileData.Size(m)
}
func (m *ProfileData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileData.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileData proto.InternalMessageInfo

func (m *ProfileData) GetAvatarType() string {
	if m != nil {
		return m.AvatarType
	}
	return ""
}

func (m *ProfileData) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ProfileData) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type ChatData struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatData) Reset()         { *m = ChatData{} }
func (m *ChatData) String() string { return proto.CompactTextString(m) }
func (*ChatData) ProtoMessage()    {}
func (*ChatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{7}
}

func (m *ChatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatData.Unmarshal(m, b)
}
func (m *ChatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatData.Marshal(b, m, deterministic)
}
func (m *ChatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatData.Merge(m, src)
}
func (m *ChatData) XXX_Size() int {
	return xxx_messageInfo_ChatData.Size(m)
}
func (m *ChatData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatData.DiscardUnknown(m)
}

var xxx_messageInfo_ChatData proto.InternalMessageInfo

func (m *ChatData) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *ChatData) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterEnum("WorldCommMessageType", WorldCommMessageType_name, WorldCommMessageType_value)
	proto.RegisterType((*WorldCommMessage)(nil), "WorldCommMessage")
	proto.RegisterType((*PingMessage)(nil), "PingMessage")
	proto.RegisterType((*AddTopicMessage)(nil), "AddTopicMessage")
	proto.RegisterType((*RemoveTopicMessage)(nil), "RemoveTopicMessage")
	proto.RegisterType((*TopicMessage)(nil), "TopicMessage")
	proto.RegisterType((*PositionData)(nil), "PositionData")
	proto.RegisterType((*ProfileData)(nil), "ProfileData")
	proto.RegisterType((*ChatData)(nil), "ChatData")
}

func init() { proto.RegisterFile("worldcomm.proto", fileDescriptor_966603bf5abd3632) }

var fileDescriptor_966603bf5abd3632 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x71, 0x97, 0x8e, 0xe5, 0x35, 0xb0, 0xc8, 0x2a, 0x52, 0x2e, 0x88, 0x92, 0x53, 0xe1,
	0xb0, 0x03, 0x9c, 0x39, 0x54, 0x6d, 0x34, 0x55, 0xa3, 0x69, 0xf0, 0x0a, 0x5d, 0xb9, 0x44, 0x6e,
	0xe3, 0x0e, 0x8b, 0xb8, 0x8e, 0x12, 0xb3, 0x2d, 0xfb, 0x0e, 0x7c, 0x4e, 0xbe, 0x06, 0x8a, 0xed,
	0xa2, 0x06, 0xed, 0xb8, 0xdd, 0xde, 0xfb, 0xff, 0x9c, 0xff, 0x7b, 0x7e, 0x2f, 0x32, 0x9c, 0xde,
	0xca, 0x32, 0xcf, 0x36, 0x52, 0x88, 0xb3, 0xa2, 0x94, 0x4a, 0x86, 0x5f, 0xc0, 0x5f, 0x36, 0xd2,
	0x58, 0x0a, 0x31, 0x63, 0x55, 0x45, 0xaf, 0x19, 0x7e, 0x07, 0x8e, 0xaa, 0x0b, 0x16, 0xa0, 0x01,
	0x1a, 0xbe, 0xfc, 0xf0, 0xea, 0xec, 0xff, 0x03, 0x8b, 0xba, 0x60, 0x44, 0x1f, 0xc1, 0x18, 0x1c,
	0xc5, 0x05, 0x0b, 0x3a, 0x03, 0x34, 0x44, 0x44, 0xc7, 0xe1, 0x67, 0xe8, 0x25, 0x7c, 0x77, 0xfd,
	0x48, 0x6e, 0x5b, 0x38, 0x1d, 0x65, 0xd9, 0x42, 0x16, 0x7c, 0xf3, 0x38, 0x8e, 0xb8, 0x0f, 0x5d,
	0xd5, 0xd8, 0x05, 0x47, 0x03, 0x34, 0x74, 0x89, 0x49, 0x42, 0x0e, 0x98, 0x30, 0x21, 0x6f, 0xd8,
	0xd3, 0x97, 0xfa, 0x8d, 0xc0, 0x7b, 0xf2, 0x2a, 0x8d, 0x4a, 0x73, 0x4e, 0xab, 0xc0, 0x31, 0xaa,
	0x4e, 0x9a, 0xef, 0xd7, 0x32, 0xab, 0x83, 0xee, 0x00, 0x0d, 0x3d, 0xa2, 0xe3, 0xf0, 0x0f, 0x02,
	0x2f, 0x91, 0x15, 0x57, 0x5c, 0xee, 0x26, 0x54, 0x51, 0xfc, 0x1a, 0xa0, 0xb0, 0x79, 0x7a, 0xa7,
	0xbb, 0xea, 0x10, 0x77, 0xaf, 0x5c, 0xb5, 0x70, 0xad, 0x3b, 0x39, 0xc0, 0xab, 0x16, 0xbe, 0xd7,
	0x3d, 0x1d, 0xe0, 0xef, 0x0d, 0x2e, 0xa5, 0xa2, 0xd6, 0xdc, 0x31, 0x78, 0xaf, 0x5c, 0xb5, 0xb0,
	0x69, 0xf3, 0x00, 0xaf, 0x5a, 0xf8, 0x3e, 0x38, 0x6e, 0xe3, 0xb6, 0xf9, 0x6d, 0xf0, 0xbc, 0x8d,
	0x97, 0x61, 0x01, 0xbd, 0xa4, 0x94, 0x5b, 0x9e, 0x33, 0x7d, 0xcf, 0x37, 0xd0, 0xa3, 0x37, 0x54,
	0xd1, 0x32, 0xfd, 0x37, 0x7e, 0x97, 0x80, 0x91, 0x9a, 0x99, 0xe3, 0xb7, 0xe0, 0x65, 0xbc, 0x2a,
	0x72, 0x5a, 0xa7, 0x3b, 0x6a, 0xa7, 0xee, 0x92, 0x9e, 0xd5, 0x62, 0x2a, 0x98, 0xbe, 0xed, 0xaf,
	0x75, 0xce, 0x37, 0xe9, 0x4f, 0x56, 0xdb, 0x0d, 0xb8, 0x46, 0xb9, 0x60, 0x75, 0xf8, 0x09, 0x4e,
	0xc6, 0x3f, 0xa8, 0xda, 0x8f, 0x55, 0x98, 0x85, 0xa6, 0x3c, 0xb3, 0xd5, 0x5c, 0xab, 0x4c, 0x33,
	0xbd, 0x5a, 0x76, 0xa7, 0x6c, 0x11, 0x1d, 0xbf, 0xdf, 0x42, 0xff, 0xa1, 0x9f, 0x01, 0x07, 0xd0,
	0xff, 0x1a, 0x5f, 0xc4, 0xf3, 0x65, 0x9c, 0xce, 0xa2, 0xcb, 0xcb, 0xd1, 0x79, 0x94, 0x2e, 0x56,
	0x49, 0xe4, 0x3f, 0xc3, 0x27, 0xe0, 0x24, 0xd3, 0xf8, 0xdc, 0x47, 0xf8, 0x05, 0xb8, 0xa3, 0xc9,
	0x24, 0x5d, 0xcc, 0x93, 0xe9, 0xd8, 0xef, 0x60, 0x1f, 0x3c, 0x12, 0xcd, 0xe6, 0xdf, 0x22, 0xab,
	0x1c, 0x61, 0x17, 0xba, 0x26, 0x74, 0xd6, 0xc7, 0xfa, 0x35, 0xf8, 0xf8, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xd9, 0x90, 0x7a, 0xd4, 0x20, 0x04, 0x00, 0x00,
}
