// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worldcomm.proto

package worldcomm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN_MESSAGE_TYPE            MessageType = 0
	MessageType_POSITION                        MessageType = 2
	MessageType_CHAT                            MessageType = 3
	MessageType_CLIENT_DISCONNECTED_FROM_SERVER MessageType = 4
	MessageType_PROFILE                         MessageType = 5
	MessageType_CLOCK_SKEW_DETECTED             MessageType = 6
	MessageType_FLOW_STATUS                     MessageType = 7
)

var MessageType_name = map[int32]string{
	0: "UNKNOWN_MESSAGE_TYPE",
	2: "POSITION",
	3: "CHAT",
	4: "CLIENT_DISCONNECTED_FROM_SERVER",
	5: "PROFILE",
	6: "CLOCK_SKEW_DETECTED",
	7: "FLOW_STATUS",
}

var MessageType_value = map[string]int32{
	"UNKNOWN_MESSAGE_TYPE":            0,
	"POSITION":                        2,
	"CHAT":                            3,
	"CLIENT_DISCONNECTED_FROM_SERVER": 4,
	"PROFILE":                         5,
	"CLOCK_SKEW_DETECTED":             6,
	"FLOW_STATUS":                     7,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{0}
}

type FlowStatus int32

const (
	FlowStatus_UNKNOWN_STATUS FlowStatus = 0
	FlowStatus_OPEN           FlowStatus = 1
	FlowStatus_CLOSE          FlowStatus = 2
)

var FlowStatus_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "OPEN",
	2: "CLOSE",
}

var FlowStatus_value = map[string]int32{
	"UNKNOWN_STATUS": 0,
	"OPEN":           1,
	"CLOSE":          2,
}

func (x FlowStatus) String() string {
	return proto.EnumName(FlowStatus_name, int32(x))
}

func (FlowStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{1}
}

type GenericMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenericMessage) Reset()         { *m = GenericMessage{} }
func (m *GenericMessage) String() string { return proto.CompactTextString(m) }
func (*GenericMessage) ProtoMessage()    {}
func (*GenericMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{0}
}

func (m *GenericMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericMessage.Unmarshal(m, b)
}
func (m *GenericMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericMessage.Marshal(b, m, deterministic)
}
func (m *GenericMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericMessage.Merge(m, src)
}
func (m *GenericMessage) XXX_Size() int {
	return xxx_messageInfo_GenericMessage.Size(m)
}
func (m *GenericMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GenericMessage proto.InternalMessageInfo

func (m *GenericMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *GenericMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type PositionMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	PositionX            float32     `protobuf:"fixed32,3,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY            float32     `protobuf:"fixed32,4,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	PositionZ            float32     `protobuf:"fixed32,5,opt,name=position_z,json=positionZ,proto3" json:"position_z,omitempty"`
	RotationX            float32     `protobuf:"fixed32,6,opt,name=rotation_x,json=rotationX,proto3" json:"rotation_x,omitempty"`
	RotationY            float32     `protobuf:"fixed32,7,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
	RotationZ            float32     `protobuf:"fixed32,8,opt,name=rotation_z,json=rotationZ,proto3" json:"rotation_z,omitempty"`
	RotationW            float32     `protobuf:"fixed32,9,opt,name=rotation_w,json=rotationW,proto3" json:"rotation_w,omitempty"`
	PeerId               string      `protobuf:"bytes,10,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PositionMessage) Reset()         { *m = PositionMessage{} }
func (m *PositionMessage) String() string { return proto.CompactTextString(m) }
func (*PositionMessage) ProtoMessage()    {}
func (*PositionMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{1}
}

func (m *PositionMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionMessage.Unmarshal(m, b)
}
func (m *PositionMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionMessage.Marshal(b, m, deterministic)
}
func (m *PositionMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionMessage.Merge(m, src)
}
func (m *PositionMessage) XXX_Size() int {
	return xxx_messageInfo_PositionMessage.Size(m)
}
func (m *PositionMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PositionMessage proto.InternalMessageInfo

func (m *PositionMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *PositionMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PositionMessage) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *PositionMessage) GetPositionY() float32 {
	if m != nil {
		return m.PositionY
	}
	return 0
}

func (m *PositionMessage) GetPositionZ() float32 {
	if m != nil {
		return m.PositionZ
	}
	return 0
}

func (m *PositionMessage) GetRotationX() float32 {
	if m != nil {
		return m.RotationX
	}
	return 0
}

func (m *PositionMessage) GetRotationY() float32 {
	if m != nil {
		return m.RotationY
	}
	return 0
}

func (m *PositionMessage) GetRotationZ() float32 {
	if m != nil {
		return m.RotationZ
	}
	return 0
}

func (m *PositionMessage) GetRotationW() float32 {
	if m != nil {
		return m.RotationW
	}
	return 0
}

func (m *PositionMessage) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type ProfileMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	PositionX            float32     `protobuf:"fixed32,3,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionZ            float32     `protobuf:"fixed32,4,opt,name=position_z,json=positionZ,proto3" json:"position_z,omitempty"`
	AvatarType           string      `protobuf:"bytes,5,opt,name=avatar_type,json=avatarType,proto3" json:"avatar_type,omitempty"`
	DisplayName          string      `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PeerId               string      `protobuf:"bytes,7,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PublicKey            string      `protobuf:"bytes,8,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProfileMessage) Reset()         { *m = ProfileMessage{} }
func (m *ProfileMessage) String() string { return proto.CompactTextString(m) }
func (*ProfileMessage) ProtoMessage()    {}
func (*ProfileMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{2}
}

func (m *ProfileMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileMessage.Unmarshal(m, b)
}
func (m *ProfileMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileMessage.Marshal(b, m, deterministic)
}
func (m *ProfileMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileMessage.Merge(m, src)
}
func (m *ProfileMessage) XXX_Size() int {
	return xxx_messageInfo_ProfileMessage.Size(m)
}
func (m *ProfileMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileMessage proto.InternalMessageInfo

func (m *ProfileMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *ProfileMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ProfileMessage) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *ProfileMessage) GetPositionZ() float32 {
	if m != nil {
		return m.PositionZ
	}
	return 0
}

func (m *ProfileMessage) GetAvatarType() string {
	if m != nil {
		return m.AvatarType
	}
	return ""
}

func (m *ProfileMessage) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ProfileMessage) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *ProfileMessage) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type ChatMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	MessageId            string      `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PositionX            float32     `protobuf:"fixed32,4,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionZ            float32     `protobuf:"fixed32,5,opt,name=position_z,json=positionZ,proto3" json:"position_z,omitempty"`
	Text                 string      `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	PeerId               string      `protobuf:"bytes,7,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{3}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *ChatMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ChatMessage) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *ChatMessage) GetPositionX() float32 {
	if m != nil {
		return m.PositionX
	}
	return 0
}

func (m *ChatMessage) GetPositionZ() float32 {
	if m != nil {
		return m.PositionZ
	}
	return 0
}

func (m *ChatMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *ChatMessage) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type ClientDisconnectedFromServerMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	PeerId               string      `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClientDisconnectedFromServerMessage) Reset()         { *m = ClientDisconnectedFromServerMessage{} }
func (m *ClientDisconnectedFromServerMessage) String() string { return proto.CompactTextString(m) }
func (*ClientDisconnectedFromServerMessage) ProtoMessage()    {}
func (*ClientDisconnectedFromServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{4}
}

func (m *ClientDisconnectedFromServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientDisconnectedFromServerMessage.Unmarshal(m, b)
}
func (m *ClientDisconnectedFromServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientDisconnectedFromServerMessage.Marshal(b, m, deterministic)
}
func (m *ClientDisconnectedFromServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDisconnectedFromServerMessage.Merge(m, src)
}
func (m *ClientDisconnectedFromServerMessage) XXX_Size() int {
	return xxx_messageInfo_ClientDisconnectedFromServerMessage.Size(m)
}
func (m *ClientDisconnectedFromServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDisconnectedFromServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDisconnectedFromServerMessage proto.InternalMessageInfo

func (m *ClientDisconnectedFromServerMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *ClientDisconnectedFromServerMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ClientDisconnectedFromServerMessage) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type ClockSkewMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClockSkewMessage) Reset()         { *m = ClockSkewMessage{} }
func (m *ClockSkewMessage) String() string { return proto.CompactTextString(m) }
func (*ClockSkewMessage) ProtoMessage()    {}
func (*ClockSkewMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{5}
}

func (m *ClockSkewMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClockSkewMessage.Unmarshal(m, b)
}
func (m *ClockSkewMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClockSkewMessage.Marshal(b, m, deterministic)
}
func (m *ClockSkewMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClockSkewMessage.Merge(m, src)
}
func (m *ClockSkewMessage) XXX_Size() int {
	return xxx_messageInfo_ClockSkewMessage.Size(m)
}
func (m *ClockSkewMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClockSkewMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClockSkewMessage proto.InternalMessageInfo

func (m *ClockSkewMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *ClockSkewMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type FlowStatusMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Time                 float64     `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	FlowStatus           FlowStatus  `protobuf:"varint,3,opt,name=flow_status,json=flowStatus,proto3,enum=FlowStatus" json:"flow_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FlowStatusMessage) Reset()         { *m = FlowStatusMessage{} }
func (m *FlowStatusMessage) String() string { return proto.CompactTextString(m) }
func (*FlowStatusMessage) ProtoMessage()    {}
func (*FlowStatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_966603bf5abd3632, []int{6}
}

func (m *FlowStatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowStatusMessage.Unmarshal(m, b)
}
func (m *FlowStatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowStatusMessage.Marshal(b, m, deterministic)
}
func (m *FlowStatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowStatusMessage.Merge(m, src)
}
func (m *FlowStatusMessage) XXX_Size() int {
	return xxx_messageInfo_FlowStatusMessage.Size(m)
}
func (m *FlowStatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowStatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FlowStatusMessage proto.InternalMessageInfo

func (m *FlowStatusMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (m *FlowStatusMessage) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *FlowStatusMessage) GetFlowStatus() FlowStatus {
	if m != nil {
		return m.FlowStatus
	}
	return FlowStatus_UNKNOWN_STATUS
}

func init() {
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("FlowStatus", FlowStatus_name, FlowStatus_value)
	proto.RegisterType((*GenericMessage)(nil), "GenericMessage")
	proto.RegisterType((*PositionMessage)(nil), "PositionMessage")
	proto.RegisterType((*ProfileMessage)(nil), "ProfileMessage")
	proto.RegisterType((*ChatMessage)(nil), "ChatMessage")
	proto.RegisterType((*ClientDisconnectedFromServerMessage)(nil), "ClientDisconnectedFromServerMessage")
	proto.RegisterType((*ClockSkewMessage)(nil), "ClockSkewMessage")
	proto.RegisterType((*FlowStatusMessage)(nil), "FlowStatusMessage")
}

func init() { proto.RegisterFile("worldcomm.proto", fileDescriptor_966603bf5abd3632) }

var fileDescriptor_966603bf5abd3632 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x4f, 0x4e, 0xdb, 0x40,
	0x18, 0xc5, 0x71, 0xfe, 0xe2, 0xcf, 0x28, 0xb8, 0xd3, 0x4a, 0x78, 0x53, 0x91, 0x86, 0x4d, 0x84,
	0x2a, 0x16, 0x54, 0x3d, 0x00, 0x72, 0x26, 0x10, 0x25, 0xd8, 0x91, 0xc7, 0x34, 0xc0, 0x66, 0x64,
	0x9c, 0xa1, 0xb5, 0xb0, 0x3d, 0x96, 0x3d, 0x60, 0xcc, 0xaa, 0xf7, 0xe8, 0x49, 0x7a, 0x88, 0xde,
	0xa9, 0xf2, 0xc4, 0x94, 0xb8, 0x55, 0xbb, 0x89, 0xd4, 0xdd, 0xe4, 0xfd, 0x26, 0xef, 0xbd, 0xef,
	0x93, 0x6d, 0xd8, 0xcd, 0x79, 0x1a, 0x2e, 0x7d, 0x1e, 0x45, 0x47, 0x49, 0xca, 0x05, 0x1f, 0x8c,
	0xa1, 0x77, 0xca, 0x62, 0x96, 0x06, 0xfe, 0x39, 0xcb, 0x32, 0xef, 0x33, 0x43, 0x7d, 0x68, 0x89,
	0x22, 0x61, 0x86, 0xd2, 0x57, 0x86, 0xbd, 0xe3, 0x9d, 0xa3, 0x4a, 0x77, 0x8b, 0x84, 0x39, 0x92,
	0x20, 0x04, 0x2d, 0x11, 0x44, 0xcc, 0x68, 0xf4, 0x95, 0xa1, 0xe2, 0xc8, 0xf3, 0xe0, 0x7b, 0x03,
	0x76, 0xe7, 0x3c, 0x0b, 0x44, 0xc0, 0xe3, 0x8d, 0x9c, 0xd0, 0x5b, 0x80, 0xa4, 0x32, 0xa2, 0x8f,
	0x46, 0xb3, 0xaf, 0x0c, 0x1b, 0x8e, 0xfa, 0xac, 0x5c, 0xd6, 0x70, 0x61, 0xb4, 0xea, 0xf8, 0xaa,
	0x86, 0x9f, 0x8c, 0x76, 0x1d, 0x5f, 0x97, 0x38, 0xe5, 0xc2, 0xab, 0xcc, 0x3b, 0x2b, 0xfc, 0xac,
	0x5c, 0xd6, 0x70, 0x61, 0x74, 0xeb, 0xf8, 0xaa, 0x86, 0x9f, 0x8c, 0xed, 0x3a, 0xae, 0x9b, 0xe7,
	0x86, 0x5a, 0xc7, 0x0b, 0xb4, 0x07, 0xdd, 0x84, 0xb1, 0x94, 0x06, 0x4b, 0x03, 0xfa, 0xca, 0x50,
	0x75, 0x3a, 0xe5, 0xcf, 0xc9, 0x72, 0xf0, 0xb5, 0x01, 0xbd, 0x79, 0xca, 0x6f, 0x83, 0x90, 0xfd,
	0xb7, 0xd5, 0x3d, 0xfd, 0xbe, 0xba, 0x6b, 0xb4, 0x0f, 0x9a, 0xf7, 0xe0, 0x09, 0x2f, 0xa5, 0x32,
	0xba, 0x2d, 0x3b, 0xc2, 0x4a, 0x2a, 0x83, 0xd1, 0x3b, 0xd8, 0x59, 0x06, 0x59, 0x12, 0x7a, 0x05,
	0x8d, 0xbd, 0x88, 0xc9, 0xf5, 0xa9, 0x8e, 0x56, 0x69, 0x96, 0x17, 0xb1, 0xf5, 0x19, 0xbb, 0xeb,
	0x33, 0xca, 0xec, 0xfb, 0x9b, 0x30, 0xf0, 0xe9, 0x1d, 0x2b, 0xe4, 0xea, 0x54, 0x47, 0x5d, 0x29,
	0x53, 0x56, 0x0c, 0x7e, 0x28, 0xa0, 0x99, 0x5f, 0x3c, 0xb1, 0xf1, 0xfc, 0xd1, 0xea, 0x62, 0x59,
	0xa0, 0xb9, 0x0a, 0xa9, 0x94, 0xaa, 0xc3, 0xcb, 0x7a, 0x5a, 0xff, 0x5e, 0xcf, 0x1f, 0x8f, 0x4e,
	0x19, 0xc8, 0x1e, 0x45, 0x35, 0xb5, 0x3c, 0xff, 0x75, 0xdc, 0x81, 0x80, 0x03, 0x33, 0x0c, 0x58,
	0x2c, 0x46, 0x41, 0xe6, 0xf3, 0x38, 0x66, 0xbe, 0x60, 0xcb, 0x71, 0xca, 0x23, 0xc2, 0xd2, 0x07,
	0x96, 0x6e, 0x36, 0xe6, 0x5a, 0x6a, 0xb3, 0x96, 0x7a, 0x06, 0xba, 0x19, 0x72, 0xff, 0x8e, 0xdc,
	0xb1, 0x7c, 0xb3, 0xd7, 0x39, 0x87, 0x57, 0xe3, 0x90, 0xe7, 0x44, 0x78, 0xe2, 0x3e, 0xdb, 0xac,
	0xed, 0x7b, 0xd0, 0x6e, 0x43, 0x9e, 0xd3, 0x4c, 0x7a, 0xc9, 0xc6, 0xbd, 0x63, 0xed, 0xe8, 0xc5,
	0xde, 0x81, 0xdb, 0x5f, 0xe7, 0xc3, 0x6f, 0x0a, 0x68, 0x6b, 0xbe, 0xc8, 0x80, 0x37, 0x17, 0xd6,
	0xd4, 0xb2, 0x17, 0x16, 0x3d, 0xc7, 0x84, 0x9c, 0x9c, 0x62, 0xea, 0x5e, 0xcd, 0xb1, 0xbe, 0x85,
	0x76, 0x60, 0x7b, 0x6e, 0x93, 0x89, 0x3b, 0xb1, 0x2d, 0xbd, 0x81, 0xb6, 0xa1, 0x65, 0x9e, 0x9d,
	0xb8, 0x7a, 0x13, 0x1d, 0xc0, 0xbe, 0x39, 0x9b, 0x60, 0xcb, 0xa5, 0xa3, 0x09, 0x31, 0x6d, 0xcb,
	0xc2, 0xa6, 0x8b, 0x47, 0x74, 0xec, 0xd8, 0xe7, 0x94, 0x60, 0xe7, 0x13, 0x76, 0xf4, 0x16, 0xd2,
	0xa0, 0x3b, 0x77, 0xec, 0xf1, 0x64, 0x86, 0xf5, 0x36, 0xda, 0x83, 0xd7, 0xe6, 0xcc, 0x36, 0xa7,
	0x94, 0x4c, 0xf1, 0x82, 0x8e, 0xb0, 0x2b, 0xff, 0xa1, 0x77, 0xd0, 0x2e, 0x68, 0xe3, 0x99, 0xbd,
	0xa0, 0xc4, 0x3d, 0x71, 0x2f, 0x88, 0xde, 0x3d, 0xfc, 0x08, 0xf0, 0xd2, 0x1b, 0x21, 0xe8, 0x3d,
	0x77, 0xab, 0x6e, 0x6c, 0x95, 0x3d, 0xec, 0x39, 0xb6, 0x74, 0x05, 0xa9, 0xd0, 0x36, 0x67, 0x36,
	0xc1, 0x7a, 0xe3, 0xa6, 0x23, 0xbf, 0xb5, 0x1f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x45,
	0xb4, 0x18, 0x7e, 0x05, 0x00, 0x00,
}
